all:
	cl uname.c
	copy uname.exe pname.exe

install:
	copy uname.exe "%WINDIR%"
	copy pname.exe "%WINDIR%"
	
uninstall:
	del "%WINDIR%\uname.exe"
	del "%WINDIR%\pname.exe"
	
dust:
	del *.obj

clean:
	del *.exe *.obj